version: '2'
services:
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "REDIS_HOST=redis"

  redis:
    image: redis
    volumes:
      - redisData:/data
    ports:
      - 6379:6379

volumes:
  dbdata:
  redisData:
